version: '2'

networks:
  app-tier:
    driver: bridge

# networks:
#   outside:
#     external: true

services:
  rabbitmq:
    image: 'rabbitmq:latest'
    # network_mode: host
    networks:
      - app-tier
    ports: 
      - 25672:25672
      - 4369:4369
      - 5671:5671
      - 5672:5672
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - 'rabbitmq_data:/var/rabbitmq'
  gateway1:
    image: 'mdimai666/gateway1'
    restart: always
    networks:
      - app-tier
    ports: 
      - 3000:3000
    # network_mode: host
    depends_on: 
      - rabbitmq
    environment: 
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672
      - PORT=3000
    
  node1:
    image: 'mdimai666/node1'
    restart: always
    networks:
      - app-tier
    ports: 
      - 3001:3001
    # network_mode: host
    depends_on: 
      - rabbitmq
    environment: 
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672
      - PORT=3001

  node2:
    image: 'mdimai666/node2'
    restart: always
    networks:
      - app-tier
    ports: 
      - 3002:3002
    # network_mode: host
    depends_on: 
      - rabbitmq
    environment: 
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672
      - PORT=3002

volumes:
  rabbitmq_data:
    driver: local


# docker-compose up -d